// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADOpfbjKs5IZPH6YQ_kAz2zn3siPlg828',
    appId: '1:1023420781869:web:f87e215bc301c80c712fa4',
    messagingSenderId: '1023420781869',
    projectId: 'kuyum-app-58519',
    authDomain: 'kuyum-app-58519.firebaseapp.com',
    storageBucket: 'kuyum-app-58519.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3eu8yOfys4x8hTgRSJ6HlrQFiP_AYi1g',
    appId: '1:1023420781869:android:2e96c942fda257a0712fa4',
    messagingSenderId: '1023420781869',
    projectId: 'kuyum-app-58519',
    storageBucket: 'kuyum-app-58519.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIRYXFylFsC1yMA3cpWxVG-iaV9OlGjtU',
    appId: '1:1023420781869:ios:bd3bb82b2b8b9f33712fa4',
    messagingSenderId: '1023420781869',
    projectId: 'kuyum-app-58519',
    storageBucket: 'kuyum-app-58519.appspot.com',
    iosBundleId: 'com.example.kuyumApp',
  );
}
